/////////////////////////////////////
// ihaiu.ExportFairyGUICode生成
// http://blog.ihaiu.com
/////////////////////////////////////


import YellowButton from "../../Extends/CommonBase/YellowButton";
import BlueButton from "../../Extends/CommonBase/BlueButton";
import CheckBox from "../../Extends/CommonBase/CheckBox";
import BaseFullWindowUI from "../../Extends/CommonBase/BaseFullWindowUI";
import CommonBadge from "../../Extends/CommonBase/CommonBadge";
import NumberBadge from "../../Extends/CommonBase/NumberBadge";
import BagTabBar from "../../Extends/CommonBase/BagTabBar";
import BaseProgressBar from "../../Extends/CommonBase/BaseProgressBar";
import Slider_grip from "../../Extends/CommonBase/Slider_grip";
import Slider from "../../Extends/CommonBase/Slider";
import YellowBigButton from "../../Extends/CommonBase/YellowBigButton";
import YellowSmallButton from "../../Extends/CommonBase/YellowSmallButton";
import BlueButtonSmall from "../../Extends/CommonBase/BlueButtonSmall";
import YellowButtonSmall from "../../Extends/CommonBase/YellowButtonSmall";
import YellowProgressBar from "../../Extends/CommonBase/YellowProgressBar";
import AddButton from "../../Extends/CommonBase/AddButton";
import Yellow2Button from "../../Extends/CommonBase/Yellow2Button";
import EmptyButton from "../../Extends/CommonBase/EmptyButton";
import ProgressBarBlue from "../../Extends/CommonBase/ProgressBarBlue";
import RenameInput from "../../Extends/CommonBase/RenameInput";
import IconButton from "../../Extends/CommonBase/IconButton";
import CellphoneButton from "../../Extends/CommonBase/CellphoneButton";
import ActorSelectTabBar from "../../Extends/CommonBase/ActorSelectTabBar";
import ChartBarItem from "../../Extends/CommonBase/ChartBarItem";
import ChartBarView from "../../Extends/CommonBase/ChartBarView";
import StudioNextButton from "../../Extends/CommonBase/StudioNextButton";
import StudioGetRewardButton from "../../Extends/CommonBase/StudioGetRewardButton";
import BigTabButton from "../../Extends/CommonBase/BigTabButton";
import BuildingPageTabBar from "../../Extends/CommonBase/BuildingPageTabBar";
import SmallCommonButton from "../../Extends/CommonBase/SmallCommonButton";
import SmallTabButton from "../../Extends/CommonBase/SmallTabButton";
import ActorListTabBar from "../../Extends/CommonBase/ActorListTabBar";
import ActorButton from "../../Extends/CommonBase/ActorButton";
import VerticalButton from "../../Extends/CommonBase/VerticalButton";
import ActorPropertyTabBar from "../../Extends/CommonBase/ActorPropertyTabBar";
import ChartPolygonPropertyView from "../../Extends/CommonBase/ChartPolygonPropertyView";
import ChartPolygonPropertyText from "../../Extends/CommonBase/ChartPolygonPropertyText";
import StoryListTabBar from "../../Extends/CommonBase/StoryListTabBar";
import BlueScaleButton from "../../Extends/CommonBase/BlueScaleButton";
import WriteButton from "../../Extends/CommonBase/WriteButton";
import ShadowMask from "../../Extends/CommonBase/ShadowMask";
import RenameInput2 from "../../Extends/CommonBase/RenameInput2";
import StudioRenameButton from "../../Extends/CommonBase/StudioRenameButton";
import PenButon from "../../Extends/CommonBase/PenButon";
import BubbleTalkSmall from "../../Extends/CommonBase/BubbleTalkSmall";
import ShareButton from "../../Extends/CommonBase/ShareButton";
import ShareButtonBar from "../../Extends/CommonBase/ShareButtonBar";
import InformationProgressBar from "../../Extends/CommonBase/InformationProgressBar";
import InformationTabBar from "../../Extends/CommonBase/InformationTabBar";
import PinkTabButton from "../../Extends/CommonBase/PinkTabButton";
import AddButton2 from "../../Extends/CommonBase/AddButton2";
import RemoveButton from "../../Extends/CommonBase/RemoveButton";
import ExitViewButton from "../../Extends/CommonBase/ExitViewButton";
import BuildingProgressBar1 from "../../Extends/CommonBase/BuildingProgressBar1";
import CloseButton from "../../Extends/CommonBase/CloseButton";
import ViewCheckButton from "../../Extends/CommonBase/ViewCheckButton";
import CloseButton3 from "../../Extends/CommonBase/CloseButton3";
import BuildingProgressBar from "../../Extends/CommonBase/BuildingProgressBar";
import ChartPolygonPropertyTextOnlyName from "../../Extends/CommonBase/ChartPolygonPropertyTextOnlyName";
import ChartProgressBar from "../../Extends/CommonBase/ChartProgressBar";
import StudioAnimatedButton from "../../Extends/CommonBase/StudioAnimatedButton";
import StudioAnimatedButton_ani from "../../Extends/CommonBase/StudioAnimatedButton_ani";
import MyInfoButton from "../../Extends/CommonBase/MyInfoButton";
import InformationScrollBar_grip from "../../Extends/CommonBase/InformationScrollBar_grip";
import InformationScrollBar from "../../Extends/CommonBase/InformationScrollBar";
import MenuButton from "../../Extends/CommonBase/MenuButton";
import PinkButton from "../../Extends/CommonBase/PinkButton";

export default class CommonBaseBinder
{
	public static bindAll():void 
	{
		let bind = fairygui.UIObjectFactory.setPackageItemExtension;
		bind(YellowButton.URL, YellowButton);
		bind(BlueButton.URL, BlueButton);
		bind(CheckBox.URL, CheckBox);
		bind(BaseFullWindowUI.URL, BaseFullWindowUI);
		bind(CommonBadge.URL, CommonBadge);
		bind(NumberBadge.URL, NumberBadge);
		bind(BagTabBar.URL, BagTabBar);
		bind(BaseProgressBar.URL, BaseProgressBar);
		bind(Slider_grip.URL, Slider_grip);
		bind(Slider.URL, Slider);
		bind(YellowBigButton.URL, YellowBigButton);
		bind(YellowSmallButton.URL, YellowSmallButton);
		bind(BlueButtonSmall.URL, BlueButtonSmall);
		bind(YellowButtonSmall.URL, YellowButtonSmall);
		bind(YellowProgressBar.URL, YellowProgressBar);
		bind(AddButton.URL, AddButton);
		bind(Yellow2Button.URL, Yellow2Button);
		bind(EmptyButton.URL, EmptyButton);
		bind(ProgressBarBlue.URL, ProgressBarBlue);
		bind(RenameInput.URL, RenameInput);
		bind(IconButton.URL, IconButton);
		bind(CellphoneButton.URL, CellphoneButton);
		bind(ActorSelectTabBar.URL, ActorSelectTabBar);
		bind(ChartBarItem.URL, ChartBarItem);
		bind(ChartBarView.URL, ChartBarView);
		bind(StudioNextButton.URL, StudioNextButton);
		bind(StudioGetRewardButton.URL, StudioGetRewardButton);
		bind(BigTabButton.URL, BigTabButton);
		bind(BuildingPageTabBar.URL, BuildingPageTabBar);
		bind(SmallCommonButton.URL, SmallCommonButton);
		bind(SmallTabButton.URL, SmallTabButton);
		bind(ActorListTabBar.URL, ActorListTabBar);
		bind(ActorButton.URL, ActorButton);
		bind(VerticalButton.URL, VerticalButton);
		bind(ActorPropertyTabBar.URL, ActorPropertyTabBar);
		bind(ChartPolygonPropertyView.URL, ChartPolygonPropertyView);
		bind(ChartPolygonPropertyText.URL, ChartPolygonPropertyText);
		bind(StoryListTabBar.URL, StoryListTabBar);
		bind(BlueScaleButton.URL, BlueScaleButton);
		bind(WriteButton.URL, WriteButton);
		bind(ShadowMask.URL, ShadowMask);
		bind(RenameInput2.URL, RenameInput2);
		bind(StudioRenameButton.URL, StudioRenameButton);
		bind(PenButon.URL, PenButon);
		bind(BubbleTalkSmall.URL, BubbleTalkSmall);
		bind(ShareButton.URL, ShareButton);
		bind(ShareButtonBar.URL, ShareButtonBar);
		bind(InformationProgressBar.URL, InformationProgressBar);
		bind(InformationTabBar.URL, InformationTabBar);
		bind(PinkTabButton.URL, PinkTabButton);
		bind(AddButton2.URL, AddButton2);
		bind(RemoveButton.URL, RemoveButton);
		bind(ExitViewButton.URL, ExitViewButton);
		bind(BuildingProgressBar1.URL, BuildingProgressBar1);
		bind(CloseButton.URL, CloseButton);
		bind(ViewCheckButton.URL, ViewCheckButton);
		bind(CloseButton3.URL, CloseButton3);
		bind(BuildingProgressBar.URL, BuildingProgressBar);
		bind(ChartPolygonPropertyTextOnlyName.URL, ChartPolygonPropertyTextOnlyName);
		bind(ChartProgressBar.URL, ChartProgressBar);
		bind(StudioAnimatedButton.URL, StudioAnimatedButton);
		bind(StudioAnimatedButton_ani.URL, StudioAnimatedButton_ani);
		bind(MyInfoButton.URL, MyInfoButton);
		bind(InformationScrollBar_grip.URL, InformationScrollBar_grip);
		bind(InformationScrollBar.URL, InformationScrollBar);
		bind(MenuButton.URL, MenuButton);
		bind(PinkButton.URL, PinkButton);
	}
}