
import {GamerLoginS2CHandler} from "./GamerLoginS2CHandler";
import {GamerLoginGetDataS2CHandler} from "./GamerLoginGetDataS2CHandler";
import {ServerTimeS2CHandler} from "./ServerTimeS2CHandler";
import {GamerNotifyLoginOtherS2CHandler} from "./GamerNotifyLoginOtherS2CHandler";
import {GamerSubChatChannelS2CHandler} from "./GamerSubChatChannelS2CHandler";
import {GamerNotifyExpLevelS2CHandler} from "./GamerNotifyExpLevelS2CHandler";
import {GamerFriendChatS2CHandler} from "./GamerFriendChatS2CHandler";
import {GamerWorldChatS2CHandler} from "./GamerWorldChatS2CHandler";
import {GamerTestChatS2CHandler} from "./GamerTestChatS2CHandler";
import {GamerClubRequestS2CHandler} from "./GamerClubRequestS2CHandler";
import {GamerNotifyNewChatS2CHandler} from "./GamerNotifyNewChatS2CHandler";
import {GamerNewFriendReqS2CHandler} from "./GamerNewFriendReqS2CHandler";
import {GamerNotifyNewFriendReqS2CHandler} from "./GamerNotifyNewFriendReqS2CHandler";
import {GamerProcessFriendReqS2CHandler} from "./GamerProcessFriendReqS2CHandler";
import {GamerNotifyNewFriendS2CHandler} from "./GamerNotifyNewFriendS2CHandler";
import {GamerNotifyMailS2CHandler} from "./GamerNotifyMailS2CHandler";
import {GamerNotifyNewMailS2CHandler} from "./GamerNotifyNewMailS2CHandler";
import {GamerGetMailS2CHandler} from "./GamerGetMailS2CHandler";
import {GamerDelMailS2CHandler} from "./GamerDelMailS2CHandler";
import {GamerDelHaveReadMailS2CHandler} from "./GamerDelHaveReadMailS2CHandler";
import {GamerOneKeyRcvMailRewardS2CHandler} from "./GamerOneKeyRcvMailRewardS2CHandler";
import {GamerChangeMailStateS2CHandler} from "./GamerChangeMailStateS2CHandler";
import {GamerMatchS2CHandler} from "./GamerMatchS2CHandler";
import {GamerNotifyMatchInfoS2CHandler} from "./GamerNotifyMatchInfoS2CHandler";
import {GamerPVPSyncS2CHandler} from "./GamerPVPSyncS2CHandler";
import {GamerNotifyPVPSyncS2CHandler} from "./GamerNotifyPVPSyncS2CHandler";
import {GamerNotifyNewPVPResultS2CHandler} from "./GamerNotifyNewPVPResultS2CHandler";
import {GamerNotifyIconChangeS2CHandler} from "./GamerNotifyIconChangeS2CHandler";
import {GamerGetRealTimeRankS2CHandler} from "./GamerGetRealTimeRankS2CHandler";
import {GamerCheckPVPBattleS2CHandler} from "./GamerCheckPVPBattleS2CHandler";
import {GamerUploadWXInfoS2CHandler} from "./GamerUploadWXInfoS2CHandler";
import {CreateLeagueS2CHandler} from "./CreateLeagueS2CHandler";
import {GamerNotifyLeagueDataS2CHandler} from "./GamerNotifyLeagueDataS2CHandler";
import {GamerNotifyLeagueGamerOnlineS2CHandler} from "./GamerNotifyLeagueGamerOnlineS2CHandler";
import {GamerGetBackpackS2CHandler} from "./GamerGetBackpackS2CHandler";
import {GamerNotifyItemS2CHandler} from "./GamerNotifyItemS2CHandler";
import {GamerSellItemS2CHandler} from "./GamerSellItemS2CHandler";
import {GamerUseItemS2CHandler} from "./GamerUseItemS2CHandler";
import {GamerCompoundItemS2CHandler} from "./GamerCompoundItemS2CHandler";
import {GamerSplitItemS2CHandler} from "./GamerSplitItemS2CHandler";
import {GamerNotifyItemChangeS2CHandler} from "./GamerNotifyItemChangeS2CHandler";
import {GamerGetActorListS2CHandler} from "./GamerGetActorListS2CHandler";
import {GamerChangeActorNameS2CHandler} from "./GamerChangeActorNameS2CHandler";
import {GamerActorUpLevelS2CHandler} from "./GamerActorUpLevelS2CHandler";
import {GamerNotifyActorChangeS2CHandler} from "./GamerNotifyActorChangeS2CHandler";
import {GamerGetActorSetListS2CHandler} from "./GamerGetActorSetListS2CHandler";
import {GamerGetActorSetRewardS2CHandler} from "./GamerGetActorSetRewardS2CHandler";
import {GamerNotifyActorSetChangeS2CHandler} from "./GamerNotifyActorSetChangeS2CHandler";
import {GamerActorSendGiftS2CHandler} from "./GamerActorSendGiftS2CHandler";
import {GamerActorLabelUpLevelS2CHandler} from "./GamerActorLabelUpLevelS2CHandler";
import {GamerActorOpenNewLabelS2CHandler} from "./GamerActorOpenNewLabelS2CHandler";
import {GamerActorBuyNewLabelS2CHandler} from "./GamerActorBuyNewLabelS2CHandler";
import {GamerActorAdNewLabelS2CHandler} from "./GamerActorAdNewLabelS2CHandler";
import {GamerActorFriendshipUpLevelS2CHandler} from "./GamerActorFriendshipUpLevelS2CHandler";
import {GamerActorFriendshipTaskReportS2CHandler} from "./GamerActorFriendshipTaskReportS2CHandler";
import {GamerActorSkillUpLevelS2CHandler} from "./GamerActorSkillUpLevelS2CHandler";
import {GMS2CHandler} from "./GMS2CHandler";
import {GamerNotifyStoryListS2CHandler} from "./GamerNotifyStoryListS2CHandler";
import {StoryGiveLikeS2CHandler} from "./StoryGiveLikeS2CHandler";
import {StoryCommentS2CHandler} from "./StoryCommentS2CHandler";
import {StoryReadCommentS2CHandler} from "./StoryReadCommentS2CHandler";
import {StoryGetCommentS2CHandler} from "./StoryGetCommentS2CHandler";
import {StoryChangeNameS2CHandler} from "./StoryChangeNameS2CHandler";
import {GamerNotifyBuildInfoS2CHandler} from "./GamerNotifyBuildInfoS2CHandler";
import {BuildLevelUpS2CHandler} from "./BuildLevelUpS2CHandler";
import {BuildEndOfLevelUpS2CHandler} from "./BuildEndOfLevelUpS2CHandler";
import {BuildBreakUpS2CHandler} from "./BuildBreakUpS2CHandler";
import {BuildSpeedUpS2CHandler} from "./BuildSpeedUpS2CHandler";
import {BuildGetProductS2CHandler} from "./BuildGetProductS2CHandler";
import {ActorEnterBuildS2CHandler} from "./ActorEnterBuildS2CHandler";
import {ActorLeaveBuildS2CHandler} from "./ActorLeaveBuildS2CHandler";
import {GamerNotifyGashaponInfoS2CHandler} from "./GamerNotifyGashaponInfoS2CHandler";
import {GamerExtractGashaponS2CHandler} from "./GamerExtractGashaponS2CHandler";
import {GamerGetAllowanceS2CHandler} from "./GamerGetAllowanceS2CHandler";
import {GetStoryExtractInfoS2CHandler} from "./GetStoryExtractInfoS2CHandler";
import {CleanStoryExtractCDS2CHandler} from "./CleanStoryExtractCDS2CHandler";
import {PurchaseStoryExtractNumS2CHandler} from "./PurchaseStoryExtractNumS2CHandler";
import {GamerNotifyIntelligenceS2CHandler} from "./GamerNotifyIntelligenceS2CHandler";
import {GamerGetIntelligenceS2CHandler} from "./GamerGetIntelligenceS2CHandler";
import {GamerChangeIntelligenceStateS2CHandler} from "./GamerChangeIntelligenceStateS2CHandler";
import {GamerIntelligenceParseS2CHandler} from "./GamerIntelligenceParseS2CHandler";
import {StudioS2CHandler} from "./StudioS2CHandler";
import {StudioStorySelectS2CHandler} from "./StudioStorySelectS2CHandler";
import {StudioActorSelectS2CHandler} from "./StudioActorSelectS2CHandler";
import {StudioMatchingDisplayEndS2CHandler} from "./StudioMatchingDisplayEndS2CHandler";
import {GamerNotifyStudioEventS2CHandler} from "./GamerNotifyStudioEventS2CHandler";
import {StudioEventOptionSelectS2CHandler} from "./StudioEventOptionSelectS2CHandler";
import {StudioStartS2CHandler} from "./StudioStartS2CHandler";
import {StudioNextStepS2CHandler} from "./StudioNextStepS2CHandler";
import {GamerNotifyStudioFirstRewardS2CHandler} from "./GamerNotifyStudioFirstRewardS2CHandler";
import {StudioContinuedListS2CHandler} from "./StudioContinuedListS2CHandler";
import {StudioContinuedReceiveS2CHandler} from "./StudioContinuedReceiveS2CHandler";
import {StudioContinuedReceiveAllS2CHandler} from "./StudioContinuedReceiveAllS2CHandler";
import {GamerNotifyDailyTaskS2CHandler} from "./GamerNotifyDailyTaskS2CHandler";
import {GamerNotifyTaskS2CHandler} from "./GamerNotifyTaskS2CHandler";
import {GamerAcceptTaskS2CHandler} from "./GamerAcceptTaskS2CHandler";
import {GamerGetTaskRewardS2CHandler} from "./GamerGetTaskRewardS2CHandler";
import {GamerGetDailyTaskActivityDegreeRewardS2CHandler} from "./GamerGetDailyTaskActivityDegreeRewardS2CHandler";
import {GamerGetGuideProgressS2CHandler} from "./GamerGetGuideProgressS2CHandler";
import {GamerSetGuideProgressS2CHandler} from "./GamerSetGuideProgressS2CHandler";

export default class ProtoHandlerList
{
		GamerLoginS2C = GamerLoginS2CHandler;
		GamerLoginGetDataS2C = GamerLoginGetDataS2CHandler;
		ServerTimeS2C = ServerTimeS2CHandler;
		GamerNotifyLoginOtherS2C = GamerNotifyLoginOtherS2CHandler;
		GamerSubChatChannelS2C = GamerSubChatChannelS2CHandler;
		GamerNotifyExpLevelS2C = GamerNotifyExpLevelS2CHandler;
		GamerFriendChatS2C = GamerFriendChatS2CHandler;
		GamerWorldChatS2C = GamerWorldChatS2CHandler;
		GamerTestChatS2C = GamerTestChatS2CHandler;
		GamerClubRequestS2C = GamerClubRequestS2CHandler;
		GamerNotifyNewChatS2C = GamerNotifyNewChatS2CHandler;
		GamerNewFriendReqS2C = GamerNewFriendReqS2CHandler;
		GamerNotifyNewFriendReqS2C = GamerNotifyNewFriendReqS2CHandler;
		GamerProcessFriendReqS2C = GamerProcessFriendReqS2CHandler;
		GamerNotifyNewFriendS2C = GamerNotifyNewFriendS2CHandler;
		GamerNotifyMailS2C = GamerNotifyMailS2CHandler;
		GamerNotifyNewMailS2C = GamerNotifyNewMailS2CHandler;
		GamerGetMailS2C = GamerGetMailS2CHandler;
		GamerDelMailS2C = GamerDelMailS2CHandler;
		GamerDelHaveReadMailS2C = GamerDelHaveReadMailS2CHandler;
		GamerOneKeyRcvMailRewardS2C = GamerOneKeyRcvMailRewardS2CHandler;
		GamerChangeMailStateS2C = GamerChangeMailStateS2CHandler;
		GamerMatchS2C = GamerMatchS2CHandler;
		GamerNotifyMatchInfoS2C = GamerNotifyMatchInfoS2CHandler;
		GamerPVPSyncS2C = GamerPVPSyncS2CHandler;
		GamerNotifyPVPSyncS2C = GamerNotifyPVPSyncS2CHandler;
		GamerNotifyNewPVPResultS2C = GamerNotifyNewPVPResultS2CHandler;
		GamerNotifyIconChangeS2C = GamerNotifyIconChangeS2CHandler;
		GamerGetRealTimeRankS2C = GamerGetRealTimeRankS2CHandler;
		GamerCheckPVPBattleS2C = GamerCheckPVPBattleS2CHandler;
		GamerUploadWXInfoS2C = GamerUploadWXInfoS2CHandler;
		CreateLeagueS2C = CreateLeagueS2CHandler;
		GamerNotifyLeagueDataS2C = GamerNotifyLeagueDataS2CHandler;
		GamerNotifyLeagueGamerOnlineS2C = GamerNotifyLeagueGamerOnlineS2CHandler;
		GamerGetBackpackS2C = GamerGetBackpackS2CHandler;
		GamerNotifyItemS2C = GamerNotifyItemS2CHandler;
		GamerSellItemS2C = GamerSellItemS2CHandler;
		GamerUseItemS2C = GamerUseItemS2CHandler;
		GamerCompoundItemS2C = GamerCompoundItemS2CHandler;
		GamerSplitItemS2C = GamerSplitItemS2CHandler;
		GamerNotifyItemChangeS2C = GamerNotifyItemChangeS2CHandler;
		GamerGetActorListS2C = GamerGetActorListS2CHandler;
		GamerChangeActorNameS2C = GamerChangeActorNameS2CHandler;
		GamerActorUpLevelS2C = GamerActorUpLevelS2CHandler;
		GamerNotifyActorChangeS2C = GamerNotifyActorChangeS2CHandler;
		GamerGetActorSetListS2C = GamerGetActorSetListS2CHandler;
		GamerGetActorSetRewardS2C = GamerGetActorSetRewardS2CHandler;
		GamerNotifyActorSetChangeS2C = GamerNotifyActorSetChangeS2CHandler;
		GamerActorSendGiftS2C = GamerActorSendGiftS2CHandler;
		GamerActorLabelUpLevelS2C = GamerActorLabelUpLevelS2CHandler;
		GamerActorOpenNewLabelS2C = GamerActorOpenNewLabelS2CHandler;
		GamerActorBuyNewLabelS2C = GamerActorBuyNewLabelS2CHandler;
		GamerActorAdNewLabelS2C = GamerActorAdNewLabelS2CHandler;
		GamerActorFriendshipUpLevelS2C = GamerActorFriendshipUpLevelS2CHandler;
		GamerActorFriendshipTaskReportS2C = GamerActorFriendshipTaskReportS2CHandler;
		GamerActorSkillUpLevelS2C = GamerActorSkillUpLevelS2CHandler;
		GMS2C = GMS2CHandler;
		GamerNotifyStoryListS2C = GamerNotifyStoryListS2CHandler;
		StoryGiveLikeS2C = StoryGiveLikeS2CHandler;
		StoryCommentS2C = StoryCommentS2CHandler;
		StoryReadCommentS2C = StoryReadCommentS2CHandler;
		StoryGetCommentS2C = StoryGetCommentS2CHandler;
		StoryChangeNameS2C = StoryChangeNameS2CHandler;
		GamerNotifyBuildInfoS2C = GamerNotifyBuildInfoS2CHandler;
		BuildLevelUpS2C = BuildLevelUpS2CHandler;
		BuildEndOfLevelUpS2C = BuildEndOfLevelUpS2CHandler;
		BuildBreakUpS2C = BuildBreakUpS2CHandler;
		BuildSpeedUpS2C = BuildSpeedUpS2CHandler;
		BuildGetProductS2C = BuildGetProductS2CHandler;
		ActorEnterBuildS2C = ActorEnterBuildS2CHandler;
		ActorLeaveBuildS2C = ActorLeaveBuildS2CHandler;
		GamerNotifyGashaponInfoS2C = GamerNotifyGashaponInfoS2CHandler;
		GamerExtractGashaponS2C = GamerExtractGashaponS2CHandler;
		GamerGetAllowanceS2C = GamerGetAllowanceS2CHandler;
		GetStoryExtractInfoS2C = GetStoryExtractInfoS2CHandler;
		CleanStoryExtractCDS2C = CleanStoryExtractCDS2CHandler;
		PurchaseStoryExtractNumS2C = PurchaseStoryExtractNumS2CHandler;
		GamerNotifyIntelligenceS2C = GamerNotifyIntelligenceS2CHandler;
		GamerGetIntelligenceS2C = GamerGetIntelligenceS2CHandler;
		GamerChangeIntelligenceStateS2C = GamerChangeIntelligenceStateS2CHandler;
		GamerIntelligenceParseS2C = GamerIntelligenceParseS2CHandler;
		StudioS2C = StudioS2CHandler;
		StudioStorySelectS2C = StudioStorySelectS2CHandler;
		StudioActorSelectS2C = StudioActorSelectS2CHandler;
		StudioMatchingDisplayEndS2C = StudioMatchingDisplayEndS2CHandler;
		GamerNotifyStudioEventS2C = GamerNotifyStudioEventS2CHandler;
		StudioEventOptionSelectS2C = StudioEventOptionSelectS2CHandler;
		StudioStartS2C = StudioStartS2CHandler;
		StudioNextStepS2C = StudioNextStepS2CHandler;
		GamerNotifyStudioFirstRewardS2C = GamerNotifyStudioFirstRewardS2CHandler;
		StudioContinuedListS2C = StudioContinuedListS2CHandler;
		StudioContinuedReceiveS2C = StudioContinuedReceiveS2CHandler;
		StudioContinuedReceiveAllS2C = StudioContinuedReceiveAllS2CHandler;
		GamerNotifyDailyTaskS2C = GamerNotifyDailyTaskS2CHandler;
		GamerNotifyTaskS2C = GamerNotifyTaskS2CHandler;
		GamerAcceptTaskS2C = GamerAcceptTaskS2CHandler;
		GamerGetTaskRewardS2C = GamerGetTaskRewardS2CHandler;
		GamerGetDailyTaskActivityDegreeRewardS2C = GamerGetDailyTaskActivityDegreeRewardS2CHandler;
		GamerGetGuideProgressS2C = GamerGetGuideProgressS2CHandler;
		GamerSetGuideProgressS2C = GamerSetGuideProgressS2CHandler;

	init()
	{
		this.GamerLoginS2C.bind(this);
		this.GamerLoginGetDataS2C.bind(this);
		this.ServerTimeS2C.bind(this);
		this.GamerNotifyLoginOtherS2C.bind(this);
		this.GamerSubChatChannelS2C.bind(this);
		this.GamerNotifyExpLevelS2C.bind(this);
		this.GamerFriendChatS2C.bind(this);
		this.GamerWorldChatS2C.bind(this);
		this.GamerTestChatS2C.bind(this);
		this.GamerClubRequestS2C.bind(this);
		this.GamerNotifyNewChatS2C.bind(this);
		this.GamerNewFriendReqS2C.bind(this);
		this.GamerNotifyNewFriendReqS2C.bind(this);
		this.GamerProcessFriendReqS2C.bind(this);
		this.GamerNotifyNewFriendS2C.bind(this);
		this.GamerNotifyMailS2C.bind(this);
		this.GamerNotifyNewMailS2C.bind(this);
		this.GamerGetMailS2C.bind(this);
		this.GamerDelMailS2C.bind(this);
		this.GamerDelHaveReadMailS2C.bind(this);
		this.GamerOneKeyRcvMailRewardS2C.bind(this);
		this.GamerChangeMailStateS2C.bind(this);
		this.GamerMatchS2C.bind(this);
		this.GamerNotifyMatchInfoS2C.bind(this);
		this.GamerPVPSyncS2C.bind(this);
		this.GamerNotifyPVPSyncS2C.bind(this);
		this.GamerNotifyNewPVPResultS2C.bind(this);
		this.GamerNotifyIconChangeS2C.bind(this);
		this.GamerGetRealTimeRankS2C.bind(this);
		this.GamerCheckPVPBattleS2C.bind(this);
		this.GamerUploadWXInfoS2C.bind(this);
		this.CreateLeagueS2C.bind(this);
		this.GamerNotifyLeagueDataS2C.bind(this);
		this.GamerNotifyLeagueGamerOnlineS2C.bind(this);
		this.GamerGetBackpackS2C.bind(this);
		this.GamerNotifyItemS2C.bind(this);
		this.GamerSellItemS2C.bind(this);
		this.GamerUseItemS2C.bind(this);
		this.GamerCompoundItemS2C.bind(this);
		this.GamerSplitItemS2C.bind(this);
		this.GamerNotifyItemChangeS2C.bind(this);
		this.GamerGetActorListS2C.bind(this);
		this.GamerChangeActorNameS2C.bind(this);
		this.GamerActorUpLevelS2C.bind(this);
		this.GamerNotifyActorChangeS2C.bind(this);
		this.GamerGetActorSetListS2C.bind(this);
		this.GamerGetActorSetRewardS2C.bind(this);
		this.GamerNotifyActorSetChangeS2C.bind(this);
		this.GamerActorSendGiftS2C.bind(this);
		this.GamerActorLabelUpLevelS2C.bind(this);
		this.GamerActorOpenNewLabelS2C.bind(this);
		this.GamerActorBuyNewLabelS2C.bind(this);
		this.GamerActorAdNewLabelS2C.bind(this);
		this.GamerActorFriendshipUpLevelS2C.bind(this);
		this.GamerActorFriendshipTaskReportS2C.bind(this);
		this.GamerActorSkillUpLevelS2C.bind(this);
		this.GMS2C.bind(this);
		this.GamerNotifyStoryListS2C.bind(this);
		this.StoryGiveLikeS2C.bind(this);
		this.StoryCommentS2C.bind(this);
		this.StoryReadCommentS2C.bind(this);
		this.StoryGetCommentS2C.bind(this);
		this.StoryChangeNameS2C.bind(this);
		this.GamerNotifyBuildInfoS2C.bind(this);
		this.BuildLevelUpS2C.bind(this);
		this.BuildEndOfLevelUpS2C.bind(this);
		this.BuildBreakUpS2C.bind(this);
		this.BuildSpeedUpS2C.bind(this);
		this.BuildGetProductS2C.bind(this);
		this.ActorEnterBuildS2C.bind(this);
		this.ActorLeaveBuildS2C.bind(this);
		this.GamerNotifyGashaponInfoS2C.bind(this);
		this.GamerExtractGashaponS2C.bind(this);
		this.GamerGetAllowanceS2C.bind(this);
		this.GetStoryExtractInfoS2C.bind(this);
		this.CleanStoryExtractCDS2C.bind(this);
		this.PurchaseStoryExtractNumS2C.bind(this);
		this.GamerNotifyIntelligenceS2C.bind(this);
		this.GamerGetIntelligenceS2C.bind(this);
		this.GamerChangeIntelligenceStateS2C.bind(this);
		this.GamerIntelligenceParseS2C.bind(this);
		this.StudioS2C.bind(this);
		this.StudioStorySelectS2C.bind(this);
		this.StudioActorSelectS2C.bind(this);
		this.StudioMatchingDisplayEndS2C.bind(this);
		this.GamerNotifyStudioEventS2C.bind(this);
		this.StudioEventOptionSelectS2C.bind(this);
		this.StudioStartS2C.bind(this);
		this.StudioNextStepS2C.bind(this);
		this.GamerNotifyStudioFirstRewardS2C.bind(this);
		this.StudioContinuedListS2C.bind(this);
		this.StudioContinuedReceiveS2C.bind(this);
		this.StudioContinuedReceiveAllS2C.bind(this);
		this.GamerNotifyDailyTaskS2C.bind(this);
		this.GamerNotifyTaskS2C.bind(this);
		this.GamerAcceptTaskS2C.bind(this);
		this.GamerGetTaskRewardS2C.bind(this);
		this.GamerGetDailyTaskActivityDegreeRewardS2C.bind(this);
		this.GamerGetGuideProgressS2C.bind(this);
		this.GamerSetGuideProgressS2C.bind(this);

	}
}
