
import {GamerLoginS2CHandler} from "./GamerLoginS2CHandler";
import {GamerLoginGetDataS2CHandler} from "./GamerLoginGetDataS2CHandler";
import {ServerTimeS2CHandler} from "./ServerTimeS2CHandler";
import {GamerNotifyLoginOtherS2CHandler} from "./GamerNotifyLoginOtherS2CHandler";
import {GamerSubChatChannelS2CHandler} from "./GamerSubChatChannelS2CHandler";
import {GamerNotifyExpLevelS2CHandler} from "./GamerNotifyExpLevelS2CHandler";
import {GamerFriendChatS2CHandler} from "./GamerFriendChatS2CHandler";
import {GamerWorldChatS2CHandler} from "./GamerWorldChatS2CHandler";
import {GamerTestChatS2CHandler} from "./GamerTestChatS2CHandler";
import {GamerClubRequestS2CHandler} from "./GamerClubRequestS2CHandler";
import {GamerNotifyNewChatS2CHandler} from "./GamerNotifyNewChatS2CHandler";
import {GamerNewFriendReqS2CHandler} from "./GamerNewFriendReqS2CHandler";
import {GamerNotifyNewFriendReqS2CHandler} from "./GamerNotifyNewFriendReqS2CHandler";
import {GamerProcessFriendReqS2CHandler} from "./GamerProcessFriendReqS2CHandler";
import {GamerNotifyNewFriendS2CHandler} from "./GamerNotifyNewFriendS2CHandler";
import {GamerNotifyMailS2CHandler} from "./GamerNotifyMailS2CHandler";
import {GamerNotifyNewMailS2CHandler} from "./GamerNotifyNewMailS2CHandler";
import {GamerGetMailS2CHandler} from "./GamerGetMailS2CHandler";
import {GamerDelMailS2CHandler} from "./GamerDelMailS2CHandler";
import {GamerDelHaveReadMailS2CHandler} from "./GamerDelHaveReadMailS2CHandler";
import {GamerOneKeyRcvMailRewardS2CHandler} from "./GamerOneKeyRcvMailRewardS2CHandler";
import {GamerChangeMailStateS2CHandler} from "./GamerChangeMailStateS2CHandler";
import {GamerMatchS2CHandler} from "./GamerMatchS2CHandler";
import {GamerNotifyMatchInfoS2CHandler} from "./GamerNotifyMatchInfoS2CHandler";
import {GamerPVPSyncS2CHandler} from "./GamerPVPSyncS2CHandler";
import {GamerNotifyPVPSyncS2CHandler} from "./GamerNotifyPVPSyncS2CHandler";
import {GamerNotifyNewPVPResultS2CHandler} from "./GamerNotifyNewPVPResultS2CHandler";
import {GamerNotifyIconChangeS2CHandler} from "./GamerNotifyIconChangeS2CHandler";
import {GamerGetRealTimeRankS2CHandler} from "./GamerGetRealTimeRankS2CHandler";
import {GamerCheckPVPBattleS2CHandler} from "./GamerCheckPVPBattleS2CHandler";
import {GamerUploadWXInfoS2CHandler} from "./GamerUploadWXInfoS2CHandler";
import {CreateLeagueS2CHandler} from "./CreateLeagueS2CHandler";
import {GamerNotifyLeagueDataS2CHandler} from "./GamerNotifyLeagueDataS2CHandler";
import {GamerNotifyLeagueGamerOnlineS2CHandler} from "./GamerNotifyLeagueGamerOnlineS2CHandler";
import {GamerGetBackpackS2CHandler} from "./GamerGetBackpackS2CHandler";
import {GamerNotifyItemS2CHandler} from "./GamerNotifyItemS2CHandler";
import {GamerSellItemS2CHandler} from "./GamerSellItemS2CHandler";
import {GamerUseItemS2CHandler} from "./GamerUseItemS2CHandler";
import {GamerCompoundItemS2CHandler} from "./GamerCompoundItemS2CHandler";
import {GamerSplitItemS2CHandler} from "./GamerSplitItemS2CHandler";
import {GamerNotifyItemChangeS2CHandler} from "./GamerNotifyItemChangeS2CHandler";
import {GMS2CHandler} from "./GMS2CHandler";
import {GamerNotifyGashaponInfoS2CHandler} from "./GamerNotifyGashaponInfoS2CHandler";
import {GamerExtractGashaponS2CHandler} from "./GamerExtractGashaponS2CHandler";
import {GamerGetAllowanceS2CHandler} from "./GamerGetAllowanceS2CHandler";
import {GamerNotifyActivitiesS2CHandler} from "./GamerNotifyActivitiesS2CHandler";
import {GetActivityRewardS2CHandler} from "./GetActivityRewardS2CHandler";

export default class ProtoHandlerList
{
		GamerLoginS2C = GamerLoginS2CHandler;
		GamerLoginGetDataS2C = GamerLoginGetDataS2CHandler;
		ServerTimeS2C = ServerTimeS2CHandler;
		GamerNotifyLoginOtherS2C = GamerNotifyLoginOtherS2CHandler;
		GamerSubChatChannelS2C = GamerSubChatChannelS2CHandler;
		GamerNotifyExpLevelS2C = GamerNotifyExpLevelS2CHandler;
		GamerFriendChatS2C = GamerFriendChatS2CHandler;
		GamerWorldChatS2C = GamerWorldChatS2CHandler;
		GamerTestChatS2C = GamerTestChatS2CHandler;
		GamerClubRequestS2C = GamerClubRequestS2CHandler;
		GamerNotifyNewChatS2C = GamerNotifyNewChatS2CHandler;
		GamerNewFriendReqS2C = GamerNewFriendReqS2CHandler;
		GamerNotifyNewFriendReqS2C = GamerNotifyNewFriendReqS2CHandler;
		GamerProcessFriendReqS2C = GamerProcessFriendReqS2CHandler;
		GamerNotifyNewFriendS2C = GamerNotifyNewFriendS2CHandler;
		GamerNotifyMailS2C = GamerNotifyMailS2CHandler;
		GamerNotifyNewMailS2C = GamerNotifyNewMailS2CHandler;
		GamerGetMailS2C = GamerGetMailS2CHandler;
		GamerDelMailS2C = GamerDelMailS2CHandler;
		GamerDelHaveReadMailS2C = GamerDelHaveReadMailS2CHandler;
		GamerOneKeyRcvMailRewardS2C = GamerOneKeyRcvMailRewardS2CHandler;
		GamerChangeMailStateS2C = GamerChangeMailStateS2CHandler;
		GamerMatchS2C = GamerMatchS2CHandler;
		GamerNotifyMatchInfoS2C = GamerNotifyMatchInfoS2CHandler;
		GamerPVPSyncS2C = GamerPVPSyncS2CHandler;
		GamerNotifyPVPSyncS2C = GamerNotifyPVPSyncS2CHandler;
		GamerNotifyNewPVPResultS2C = GamerNotifyNewPVPResultS2CHandler;
		GamerNotifyIconChangeS2C = GamerNotifyIconChangeS2CHandler;
		GamerGetRealTimeRankS2C = GamerGetRealTimeRankS2CHandler;
		GamerCheckPVPBattleS2C = GamerCheckPVPBattleS2CHandler;
		GamerUploadWXInfoS2C = GamerUploadWXInfoS2CHandler;
		CreateLeagueS2C = CreateLeagueS2CHandler;
		GamerNotifyLeagueDataS2C = GamerNotifyLeagueDataS2CHandler;
		GamerNotifyLeagueGamerOnlineS2C = GamerNotifyLeagueGamerOnlineS2CHandler;
		GamerGetBackpackS2C = GamerGetBackpackS2CHandler;
		GamerNotifyItemS2C = GamerNotifyItemS2CHandler;
		GamerSellItemS2C = GamerSellItemS2CHandler;
		GamerUseItemS2C = GamerUseItemS2CHandler;
		GamerCompoundItemS2C = GamerCompoundItemS2CHandler;
		GamerSplitItemS2C = GamerSplitItemS2CHandler;
		GamerNotifyItemChangeS2C = GamerNotifyItemChangeS2CHandler;
		GMS2C = GMS2CHandler;
		GamerNotifyGashaponInfoS2C = GamerNotifyGashaponInfoS2CHandler;
		GamerExtractGashaponS2C = GamerExtractGashaponS2CHandler;
		GamerNotifyActivitiesS2C = GamerNotifyActivitiesS2CHandler;
		GetActivityRewardS2C = GetActivityRewardS2CHandler;

	init()
	{
		this.GamerLoginS2C.bind(this);
		this.GamerLoginGetDataS2C.bind(this);
		this.ServerTimeS2C.bind(this);
		this.GamerNotifyLoginOtherS2C.bind(this);
		this.GamerSubChatChannelS2C.bind(this);
		this.GamerNotifyExpLevelS2C.bind(this);
		this.GamerFriendChatS2C.bind(this);
		this.GamerWorldChatS2C.bind(this);
		this.GamerTestChatS2C.bind(this);
		this.GamerClubRequestS2C.bind(this);
		this.GamerNotifyNewChatS2C.bind(this);
		this.GamerNewFriendReqS2C.bind(this);
		this.GamerNotifyNewFriendReqS2C.bind(this);
		this.GamerProcessFriendReqS2C.bind(this);
		this.GamerNotifyNewFriendS2C.bind(this);
		this.GamerNotifyMailS2C.bind(this);
		this.GamerNotifyNewMailS2C.bind(this);
		this.GamerGetMailS2C.bind(this);
		this.GamerDelMailS2C.bind(this);
		this.GamerDelHaveReadMailS2C.bind(this);
		this.GamerOneKeyRcvMailRewardS2C.bind(this);
		this.GamerChangeMailStateS2C.bind(this);
		this.GamerMatchS2C.bind(this);
		this.GamerNotifyMatchInfoS2C.bind(this);
		this.GamerPVPSyncS2C.bind(this);
		this.GamerNotifyPVPSyncS2C.bind(this);
		this.GamerNotifyNewPVPResultS2C.bind(this);
		this.GamerNotifyIconChangeS2C.bind(this);
		this.GamerGetRealTimeRankS2C.bind(this);
		this.GamerCheckPVPBattleS2C.bind(this);
		this.GamerUploadWXInfoS2C.bind(this);
		this.CreateLeagueS2C.bind(this);
		this.GamerNotifyLeagueDataS2C.bind(this);
		this.GamerNotifyLeagueGamerOnlineS2C.bind(this);
		this.GamerGetBackpackS2C.bind(this);
		this.GamerNotifyItemS2C.bind(this);
		this.GamerSellItemS2C.bind(this);
		this.GamerUseItemS2C.bind(this);
		this.GamerCompoundItemS2C.bind(this);
		this.GamerSplitItemS2C.bind(this);
		this.GamerNotifyItemChangeS2C.bind(this);
		this.GMS2C.bind(this);
		this.GamerNotifyGashaponInfoS2C.bind(this);
		this.GamerExtractGashaponS2C.bind(this);
		this.GamerNotifyActivitiesS2C.bind(this);
		this.GetActivityRewardS2C.bind(this);

	}
}
